name: Release Workflow

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

jobs:
  github_release:
    uses: verplankedev/.github/.github/workflows/github-release.yml@main

