name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  github_release:
    uses: verplankedev/.github/.github/workflows/github-release.yml@main
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

