name: Create Github Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }} # guard, only run workflow on main branch

    name: Github Release
    uses: verplankedev/.github/.github/workflows/github-release.yml@main
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
