name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  deploy_to_heroku:
#    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    runs-on: ubuntu-22.04

    name: Deploy ${{ github.ref_name }}

    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#          ref: ${{ github.ref }}

      - name: Output workflow_dispatch
        run: ${{ github.event.workflow_dispatch.sender }}

#      - uses: akhileshns/heroku-deploy@v3.12.14
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ github }}
#          team: noprotocol
#          branch: ${{ github.ref }}
