name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  deploy_to_heroku:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    name: Deploy ${{ github.ref_name }}

    uses: verplankedev/.github/.github/workflows/heroku-deploy.yml@main
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
