name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  deploy_to_heroku:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    runs-on: ubuntu-22.04

    name: Deploy ${{ github.ref_name }} to

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "github-actions-test"
          heroku_email: "job-not-existing-email-address@noprotocol.nl"
          branch: ${{ github.ref }}
