name: Generate PHP Code Coverage Report

on:
  workflow_dispatch:
    inputs:
      php:
        required: true
        default: '8.1'
        description: 'Generate code coverage report using selected PHP version'
        type: choice
        options:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'

jobs:
#  credentials:
#    runs-on: ubuntu-latest
#    outputs:
#      FOO: ${{ steps.credentials.outputs.FOO }}
#      APP_ENV: ${{ steps.credentials.outputs.APP_ENV }}
#
#    steps:
#      - name: Output encoded credentials
#        id: credentials
#        env:
#          FOO: ${{ secrets.FOO }}
#          APP_ENV: ${{ secrets.APP_ENV }}
#        run: |
#          echo "FOO=$(echo FOO)" >> $GITHUB_OUTPUT
#          echo "APP_ENV=$(echo APP_ENV)" >> $GITHUB_OUTPUT

  code_coverage:
#    needs: credentials

    name: Generate Code Coverage
    uses: verplankedev/.github/.github/workflows/php-code-coverage.yml@main
    secrets:
      env_vars: |
        APP_NAME="TestApp"
        DB_USERNAME="root"
#
#    with:
#      DB_PORT: ${{ job.services.mysql.ports[3306] }}
#      DB_USERNAME: root
#      AWS_ACCESS_KEY_ID: randomKey
#      AWS_SECRET_ACCESS_KEY: randomSecret
