name: Generate PHP Code Coverage Report

on:
  workflow_dispatch:
    inputs:
      php:
        required: true
        default: '8.1'
        description: 'Generate code coverage report using selected PHP version'
        type: choice
        options:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'

jobs:
  credentials:
    runs-on: ubuntu-latest
    outputs:
      CREDENTIAL1: ${{ steps.credentials.outputs.CREDENTIAL1 }}
      CREDENTIAL2: ${{ steps.credentials.outputs.CREDENTIAL2 }}

    steps:
      - name: Output encoded credentials
        id: credentials
        env:
          CREDENTIAL1: ${{ secrets.CREDENTIAL1 }}
          CREDENTIAL2: ${{ secrets.CREDENTIAL2 }}
        run: |
          echo "CREDENTIAL1=$(echo $CREDENTIAL1 | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "CREDENTIAL2=$(echo $CREDENTIAL2 | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT

  code_coverage:
    needs: credentials

    name: Generate Code Coverage
    uses: verplankedev/.github/.github/workflows/php-code-coverage.yml@main
    secrets:
      env_vars: |
        CREDENTIAL1=${{ needs.credentials.outputs.CREDENTIAL1 }}
        CREDENTIAL2=${{ needs.credentials.outputs.CREDENTIAL2 }}
        FOO=BAR
        APP_ENV=testing
#
#    with:
#      DB_PORT: ${{ job.services.mysql.ports[3306] }}
#      DB_USERNAME: root
#      AWS_ACCESS_KEY_ID: randomKey
#      AWS_SECRET_ACCESS_KEY: randomSecret
