name: PHPUnit Code Coverage

on:
  workflow_dispatch:

jobs:
  code_coverage:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: Code Coverage

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: pcov

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install & Cache Composer Dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist"

      - name: Copy Environment File
        run: cp .env.ci .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Generate Code Coverage
        run: php artisan test --parallel --coverage-html docs/coverage

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ github.ref_name }}
          path: docs/coverage
          retention-days: 7
