name: Create Sentry Release

on:
  release:
    types: [published]

jobs:
  sentry_release:
    name: Sentry Release
    uses: verplankedev/.github/.github/workflows/sentry-release.yml@main
    secrets: inherit
