name: Sentry Release

on:
  release:
    types: [published]

jobs:
  sentry_release:
    runs-on: ubuntu-22.04

    name: Sentry Release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: noprotocol
          SENTRY_PROJECT: ptw-api
        with:
          environment: production
          version: ${{ github.event.release.tag_name }}
