name: Static Analysis

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'fix/**'
    paths-ignore:
      - '**.md'

jobs:
  phpstan:
    name: Github Release
    uses: verplankedev/.github/.github/workflows/php-static-analysis.yml@main
    with:
      php: '8.3'
